require 'selenium-webdriver'
require 'rautomation'
require 'Win32API'


require 'rspec'
require 'db_operation_class.rb'
require 'assertion_functions'
require 'assertion_values'
require 'browser_instance_functions'
require 'sign_in'
require 'express_delivery'
#require 'express_delivery_five_one'
#require 'package'
#require 'external_source_configuration'
require 'sign_out'
require 'received_deliveries'
require 'secure_reply'
require 'user_pref_config'
require 'manage_exchage_server'
require 'user_edit'
require 'user_creation'
require 'applet_settings'
require 'user_profile'
require 'user_quota_configuration'
require 'home'
require 'limited_sender_configuration'
require 'gal'
require 'gal_list_integration'
require 'ad_connector_functionality'
#require 'contacts'
require 'open_ldap'
require 'sun_one_ldap'
require 'self_registration'
require 'complaince_settings'

require 'contacts'
require 'sent_deliveries'
#require 'reports'
#require 'file_restriction'
#require 'manage_quota_usage'
#require 'Antivirus'
require 'Antivirus_functionality'

#require 'pause_script'

require 'server_config'
require 'server_configuration_rspec'
#require 'user_pref_config'
require 'package'
#require 'received_deliveries'
require 'secure_reply'
require 'tos'
require 'limited_sender_configuration'
require 'limited_sender_functionality'
#require 'limited_sender_role'
require 'user_create'


#require 'general_test'
require 'compliance_operations'
require 'complaince_settings'
require 'workspace_configuration'
require 'workspace_applet'
require 'complaince_settings'
require 'admin_approval'
require 'account_check'
require 'user_settings'
require 'constant'
require 'deliver_app'
require 'received_deliveries'
require 'session_configuration'
require 'session_testing'
require 'collaboration'
require 'email'
require 'file_download_enhancements'
require 'link_operations'
require 'manage_quota_usage'
require 'ad_configuration'
require 'file_restriction'
#require 'Applet'
require 'session_configuration'
require 'AllAutomation/Branding'
require 'AllAutomation/Antivirus'
require 'AllAutomation/secure_reply_enhancement'
require 'accept_alert'

