Sign_in_confirmation_value = 'Sign out'
Sign_in_fail_confirmation_value = 'Invalid sign in information provided. Please try again.'
User_locked_for_invalid_password_value = 'Invalid username or password, or the account has been locked. Please try again later or contact a system administrator.'
Sign_out_confirmation_value = 'Please enter your username and password to sign in'
Sign_in_page_confirmation_value = 'Please enter your username and password to sign in'
Pending_user_approved_confirmation_value = 'Successfully activated user account '
