require 'rubygems'
require 'selenium-webdriver'
require 'rautomation'
require 'rspec/expectations'
require 'mail'

require 'sign_in_Cosmetic'
require 'menu_test_Cosmetic'
require 'profile_settings_Cosmetic'
require 'find_text_Cosmetic'
require 'button_checker_Cosmetic'
require 'server_configuration_Cosmetic'